parameters:
    liuggio_stats_d_client.collector.increment.class: AdrienBrault\StatsDCollector\Collector\IncrementCollector
    liuggio_stats_d_client.collector.memory.class: AdrienBrault\StatsDCollector\Collector\MemoryCollector
    liuggio_stats_d_client.collector.time.class: AdrienBrault\StatsDCollector\Collector\TimeCollector
    liuggio_stats_d_client.collector.exception.class: AdrienBrault\StatsDCollector\Collector\ExceptionCollector
    liuggio_stats_d_client.collector.doctrine.class: AdrienBrault\StatsDCollector\Collector\DoctrineDbalCollector
    liuggio_stats_d_client.collector.solarium.class: AdrienBrault\StatsDCollector\Collector\SolariumCollector

services:
    liuggio_stats_d_client.collector.increment:
        class: %liuggio_stats_d_client.collector.increment.class%
        abstract: true

    liuggio_stats_d_client.collector.memory:
        class: %liuggio_stats_d_client.collector.memory.class%
        abstract: true

    liuggio_stats_d_client.collector.time:
        class: %liuggio_stats_d_client.collector.time.class%
        abstract: true

    liuggio_stats_d_client.collector.exception:
        class: %liuggio_stats_d_client.collector.exception.class%
        abstract: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # TODO
    liuggio_stats_d_client.collector.doctrine:
        class: %liuggio_stats_d_client.collector.doctrine.class%
        abstract: true

    # TODO
    liuggio_stats_d_client.collector.solarium:
        class: %liuggio_stats_d_client.collector.solarium.class%
        abstract: true
